[package]
name = "builder"
version = "0.2.0"
authors = ["Lucas Fernandes Gonçalves Nogueira <lucas@quasar.dev>", "Daniel Thompson-Yvetot <denjell@sfosc.org>"]
license = "MIT"
homepage = "https://tauri-apps.org"
repository = "https://github.com/tauri-apps/tauri"
description = "Make tiny, secure apps for all desktop platforms with Tauri"
edition = "2018"
exclude = ["test/fixture/**"]


[dependencies]
tauri_includedir_codegen = "0.5.1"
serde_json = "1.0.44"
serde = "1.0"
serde_derive = "1.0"
rand = "0.7"
web-view = "0.5.4"


[features]
edge = ["web-view/edge"]
dev-server = []
embedded-server = []
no-server = []
all-api = []
readTextFile = []
readBinaryFile = []
writeFile = []
listFiles = []
listDirs = []
setTitle = []
execute = []
open = []
emit = []